config/routes.rb
Rails.application.routes.draw do
  resources :flights, only: [:index]
  resources :bookings, only: [:show, :new, :create]

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "flights#index"
end

app/models/airport.rb
class Airport < ApplicationRecord
  has_many :departing_flights, foreign_key: 'departure_airport_id', class_name: 'Flight'
  has_many :arriving_flights, foreign_key: 'arrival_airport_id', class_name: 'Flight'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  has_many :passengers
  accepts_nested_attributes_for :passengers
  belongs_to :flight
end

app/models/flight.rb
class Flight < ApplicationRecord
  belongs_to :departure_airport, class_name: 'Airport'
  belongs_to :arrival_airport, class_name: 'Airport'
  has_many :bookings
  has_many :passengers
end

app/models/passenger.rb
class Passenger < ApplicationRecord
  has_many :flights
  belongs_to :booking
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def show
    @booking = Booking.find(params[:id])
    @flight = @booking.flight
    @passengers = @booking.passengers
  end

  def new
    @flight = Flight.find(flight_params['flight_id'])
    @num_passengers = flight_params['passengers']
    @booking = Booking.new
    @num_passengers.to_i.times { @booking.passengers.build }
  end

  def create
    @flight = Flight.find(params['booking']['flight_id'])
    @booking = @flight.bookings.build(booking_params)
    passengers = @booking.passengers.map {|passenger| { name: passenger.name, email: passenger.email } }
    PassengerMailer.with(passengers: passengers).confirmation_email.deliver_later
    if @booking.save
      redirect_to @booking
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def flight_params
    params.require(:booking).permit(:flight_id, :passengers)
  end

  def booking_params
    params.require(:booking).permit(passengers_attributes: %i[name email])
  end
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
  def index
    @airport_options = Airport.all.map { |a| [a.code, a.id] }
    @flight_dates = Flight.all.map { |f| [f.departure_date.strftime('%Y/%m/%d')] }.uniq.sort
    @flight = Flight.all
    @available_flights = Flight.where(flight_params) if params.key? :flight
  end

  private

  def flight_params
    params.require(:flight).permit(:departure_airport_id, :arrival_airport_id, :departure_date)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/views/bookings/_flight.html.erb
<div class="flight">
  <h3>Chosen flight</h3>
  <table>
  <thead>
    <th>Flight ID</th><th>Departure Airport</th><th>Arrival Airport</th><th>Date</th><th>Duration</th>
    <% unless @num_passengers.nil? %>
      <th>Passengers</th>
    <% end %>
  </thead>
  <tbody>
    <tr>
    <td><%= @flight.id %></td>
    <td><%= @flight.departure_airport.code %></td>
    <td><%= @flight.arrival_airport.code %></td>
    <td><%= @flight.departure_date.strftime('%Y/%m/%d') %></td>
    <td><%= @flight.duration %> hours</td>
    <td><%= @num_passengers %></td>
      </tr>
  </tbody>
  </table>
</div>

app/views/bookings/_form.html.erb
<div class="passenger-form">
  <h3>Passenger Information</h3>
  <%= form_with model: @booking, url: bookings_path do |form| %>
    <%= form.hidden_field :flight_id, :value => @flight.id %>
    <%= form.fields_for :passengers do |sub_form| %>
      <div>Passenger <%= sub_form.options[:child_index] + 1 %>:</div>
      <%= sub_form.label :name %>
      <%= sub_form.text_field :name, required: true %>
      <%= sub_form.label :email %>
      <%= sub_form.text_field :email, required: true %>
      
    <% end %>
    <%= form.submit 'Book flight' %>
  <% end %>
</div>

app/views/bookings/_passenger_info.html.erb
<% @passengers.each_with_index do |passenger, index| %>
  <div><strong>Passenger <%= :index %></strong></div>
  <div>Name: <%= passenger.name %></div>
  <div>Email: <%= passenger.email %></div>
<% end %>

app/views/bookings/new.html.erb
<h1>Booking</h1>

<%= render partial: 'flight' %>

<%= render partial: 'form' %>

app/views/bookings/show.html.erb
<h1>Booking</h1>

<%= render partial: 'flight' %>

<%= render partial: 'passenger_info', passengers: @passengers %>

app/views/flights/_available_flights.html.erb
<div>
  <h1>Available Flights</h1>
  <% if !@available_flights.nil? && @available_flights.exists? %>
  <%= form_with url: new_booking_path, method: 'GET' do |form| %>
    <table>
      <thead>
        <th></th><th>Departure Airport</th><th>Arrival Airport</th><th>Date</th><th>Duration</th>
      </thead>
      <tbody>
        <% @available_flights.each do |av| %>
          <tr>
          <td><%= form.radio_button '[booking]flight_id', av.id %></td>
          <td><%= av.departure_airport.code %></td>
          <td><%= av.arrival_airport.code %></td>
          <td><%= av.departure_date.strftime('%Y/%m/%d') %></td>
          <td><%= av.duration %> hours</td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <%= form.hidden_field '[booking]passengers', :value => params[:flight][:passengers] %>
  <%= form.submit 'Choose flight' %>
  <% end %>

<% else %>
  <h3>No flights found :(</h1>
<% end %>
</div>

app/views/flights/_search.html.erb
<div>
  <h1>Search for flights</h1>
  <%= form_with model: @flight, url: root_path, method: 'GET' do |form| %>
    <%= form.label :departure_airport_id %>
    <%= form.select :departure_airport_id, @airport_options %>

    <%= form.label :arrival_airport_id %>
    <%= form.select :arrival_airport_id, @airport_options %>

    <%= form.label :departure_date %>
    <%= form.select :departure_date, @flight_dates %>
    
    <%= form.label :passengers %>
    <%= form.select :passengers, 1..4 %>

    <br><%= form.submit 'Search' %>
  <% end %>
<div>

app/views/flights/index.html.erb
<h1>Flights</h1>

<%= render partial: 'search' %>

<%= render partial: 'available_flights' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FlightBooker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>